// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQrqkg68ujt4P8gb1LIII0GHuokrkRCVY',
    appId: '1:999976318007:web:9e815238f082bc82433bb2',
    messagingSenderId: '999976318007',
    projectId: 'loginpg-7aad8',
    authDomain: 'loginpg-7aad8.firebaseapp.com',
    storageBucket: 'loginpg-7aad8.firebasestorage.app',
    measurementId: 'G-2XE7D94TQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF6Z_Nbsq3SHOlJv50d4Pxiq5lGHb3g1I',
    appId: '1:999976318007:android:76853c451d55c454433bb2',
    messagingSenderId: '999976318007',
    projectId: 'loginpg-7aad8',
    storageBucket: 'loginpg-7aad8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOE87etlHka4Y9et5SqTjKTg0DPLj3FaE',
    appId: '1:999976318007:ios:70b2dd4d1b81a554433bb2',
    messagingSenderId: '999976318007',
    projectId: 'loginpg-7aad8',
    storageBucket: 'loginpg-7aad8.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOE87etlHka4Y9et5SqTjKTg0DPLj3FaE',
    appId: '1:999976318007:ios:70b2dd4d1b81a554433bb2',
    messagingSenderId: '999976318007',
    projectId: 'loginpg-7aad8',
    storageBucket: 'loginpg-7aad8.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQrqkg68ujt4P8gb1LIII0GHuokrkRCVY',
    appId: '1:999976318007:web:323b22328afb3331433bb2',
    messagingSenderId: '999976318007',
    projectId: 'loginpg-7aad8',
    authDomain: 'loginpg-7aad8.firebaseapp.com',
    storageBucket: 'loginpg-7aad8.firebasestorage.app',
    measurementId: 'G-66D8WYD7MD',
  );
}
